import pandas as pd
from snakemake.utils import min_version

min_version("6.0")

configfile: "config/config.yaml"


samples_df = pd.read_csv(config["samplesheet"], sep="\t",
                      dtype={"sample_id" : "string"}
                      )

SAMPLES = samples_df.sample_id.to_list()

include: "rules/common.smk"
include: "rules/centrifuge.smk"
include: "rules/kraken2.smk"
include: "rules/kaiju.smk"


rule all:
    input:
        expand(
            [
            "results/{sample}/centrifuge/{sample}.centrifuge.out",
            "results/{sample}/centrifuge/{sample}.centrifuge.kreport.txt",
            "results/{sample}/kraken2/{sample}.kraken2.out",
            "results/{sample}/kaiju/{sample}.kaiju.names.out",
            "results/{sample}/kaiju/{sample}.{rank}.kaiju_table.tsv",
            ],
            sample=SAMPLES,
            rank=["phylum", "order", "class", "family", "genus", "species"]
        )
