samplesheet: "config/samples.tsv"

centrifuge:
  # Use the prefix of the .cf files
  index: "/net/mgx/linuxhome/mgx/databases/centrifuge/nt/nt"

kraken2:
  # Use the directory name where all db files are stored
  index: "/net/mgx/linuxhome/mgx/programs/kraken2/k2_pluspf_20210517"

kaiju:
  # Use the exact path to the fmi file
  index: "/net/mgx/linuxhome/mgx/programs/kaiju/nr_euk_20210224/kaiju_db_nr_euk.fmi"
  # Use the exact path to the nodes file
  nodes_dmp: "/net/mgx/linuxhome/mgx/programs/kaiju/nr_euk_20210224/nodes.dmp"
